language: java
jdk:
  - openjdk12
addons:
  sonarcloud:
    organization: "brielino"
    token: "42458880cca1895d2a6f4171d8162394d47967ae"
  
install:
   - mvn clean install -Drat.skip=true -Drat.numUnapprovedLicenses=200
script:
   - mvn clean package 
