language: java
jdk:
  - openjdk8
  
addons:
 sonarcloud:
  organization: brielino
  token: 85bd1d38efd55f2da622d6f56b7812b8aa00d37e

script:
  - mvn verify -Drat.numUnapprovedLicense=100 -Dlicense.skip=true -Drat.ignoreErrors=true
