
language: java
jdk:
  - openjdk11
addons:
  sonarcloud:
    organization: "brielino"
    token: "42458880cca1895d2a6f4171d8162394d47967ae"
script:
   - mvn sonar:sonar -Dsonar.projectKey=brielino_tajo 
