language: java
sudo: false
jdk:
  - openjdk11
addons:
  sonarcloud:
    organization: "brielino"
    token: "8a2f6a3794a467ce8b8cb972e023300a4a660c4e"
script:
   - mvn sonar:sonar -Dsonar.projectKey=brielino_tajo
